const Barangay = [
    { value: 'Acacia' },
    { value: 'Agdao' },
   // { value: 'Alambre' },
   // { value: 'Alejandra Navarro' },
   // { value: 'Alfonso Angliongto Sr.' },
   // { value: 'Angalan' },
   // { value: 'Atan-awe' },
   // { value: 'Baganihan' },
    { value: 'Bago Aplaya' },
    { value: 'Bago Gallera' },
    { value: 'Bago Oshiro' },
  //  { value: 'Baguio' },
  //  { value: 'Balengaeng' },
   // { value: 'Baliok' },
   // { value: 'Bangkas Heights' },
  //  { value: 'Bantol' },
    { value: 'Baracatan' },
    { value: 'Barangay 10-A' },
    { value: 'Barangay 11-B' },
    { value: 'Barangay 12-B' },
    { value: 'Barangay 13-B' },
    { value: 'Barangay 14-B' },
    { value: 'Barangay 15-B' },
    { value: 'Barangay 16-B' },
    { value: 'Barangay 17-B' },
    { value: 'Barangay 18-B' },
    { value: 'Barangay 19-B' },
    { value: 'Barangay 1-A' },
    { value: 'Barangay 20-B' },
    { value: 'Barangay 21-C' },
    { value: 'Barangay 22-C' },
    { value: 'Barangay 23-C' },
    { value: 'Barangay 24-C' },
    { value: 'Barangay 25-C' },
    { value: 'Barangay 13-B' },
    { value: 'Barangay 14-B' },
    { value: 'Barangay 15-B' },
    { value: 'Barangay 16-B' },
    { value: 'Barangay 17-B' },
    { value: 'Barangay 18-B' },
    { value: 'Barangay 19-B' },
    { value: 'Barangay 1-A' },
    { value: 'Barangay 20-B' },
    { value: 'Barangay 21-C' },
    { value: 'Barangay 22-C' },
    { value: 'Barangay 23-C' },
    { value: 'Barangay 24-C' },
    { value: 'Barangay 25-C' },
    { value: 'Barangay 4-A' },
    { value: 'Barangay 5-A' },
    { value: 'Barangay 6-A' },
    { value: 'Barangay 7-A' },
    { value: 'Barangay 8-A' },
    { value: 'Barangay 9-A' },
    // { value: 'Bato' },
    // { value: 'Bayabas' },
    // { value: 'Biao Escuela' },
    // { value: 'Biao Guianga' },
    // { value: 'Biao Joaquin' },
    // { value: 'Binugao' },
    // { value: 'Bucana' },
    // { value: 'Buda' },
    { value: 'Buhangin' },
    { value: 'Bunawan' },
    { value: 'Cabantian' },
    // { value: 'Cadalian' },
    { value: 'Calinan' },
   // { value: 'Callawa' },
    { value: 'Camansi' },
    { value: 'Carmen' },
    { value: 'Catalunan Grande' },
    { value: 'Catalunan Pequeño' },
    // { value: 'Catigan' },
    // { value: 'Cawayan' },
    // { value: 'Centro' },
    // { value: 'Colosas' },
    // { value: 'Communal' },
   // { value: 'Crossing Bayabas' },
   // { value: 'Dacudao' },
   // { value: 'Dalag' },
   // { value: 'Dalagdag' },
   // { value: 'Daliao' },
   // { value: 'Daliaon Plantation' },
   // { value: 'Datu Salumay' },
   // { value: 'Dominga' },
   // { value: 'Dumoy' },
   // { value: 'Eden' },
   // { value: 'Fatima' },
   // { value: 'Gatungan' },
   // { value: 'Gov. Paciano Bangoy' },
    { value: 'Gov. Vicente Duterte' },
   // { value: 'Gumalang' },
   // { value: 'Gumitan' },
    { value: 'Ilang' },
  //  { value: 'Inayangan' },
    { value: 'Indangan' },
 //   { value: 'Kap. Tomas Monteverde, Sr.' },
  //  { value: 'Kilate' },
   // { value: 'Lacson' },
   // { value: 'Lamanan' },
   // { value: 'Lampianao' },
   // { value: 'Langub' },
   // { value: 'Lapu-lapu' },
   // { value: 'Leon Garcia, Sr.' },
   // { value: 'Lizada' },
   // { value: 'Los Amigos' },
  //  { value: 'Lubogan' },
  //  { value: 'Lumiad' },
    { value: 'Ma-a' },
  //  { value: 'Mabuhay' },
    { value: 'Magsaysay' },
    { value: 'Magtuod' },
  //  { value: 'Mahayag' },
 //   { value: 'Malabog' },
 //   { value: 'Malagos' },
 //   { value: 'Malamba' },
 //   { value: 'Manambulan' },
    { value: 'Mandug' },
 //   { value: 'Manuel Guianga' },
  //  { value: 'Mapula' },
  //  { value: 'Marapangi' },
    { value: 'Marilog' },
    { value: 'Matina Aplaya' },
    { value: 'Matina Biao' },
    { value: 'Matina Crossing' },
    { value: 'Matina Pangi' },
  //  { value: 'Megkawayan' },
    { value: 'Mintal' },
  //  { value: 'Mudiang' },
    { value: 'Mulig' },
   // { value: 'New Carmen' },
    { value: 'New Valencia' },
    { value: 'Pampanga' },
    { value: 'Panacan' },
  //  { value: 'Panalum' },
   // { value: 'Pandaitan' },
   // { value: 'Pangyan' },
   // { value: 'Paquibato' },
   // { value: 'Paradise Embak' },
   // { value: 'Rafael Castillo' },
   // { value: 'Riverside' },
  //  { value: 'Salapawan' },
    { value: 'Salaysay' },
    // { value: 'Saloy' },
    { value: 'San Antonio' },
    { value: 'San Isidro' },
    { value: 'Santo Niño' },
    { value: 'Sasa' },
    // { value: 'Sibulan' },
    // { value: 'Sirawan' },
    // { value: 'Sirib' },
 //   { value: 'Paquibato' },
    // { value: 'Paradise Embak' },
    // { value: 'Rafael Castillo' },
  //  { value: 'Riverside' },
    // { value: 'Salapawan' },
    // { value: 'Salaysay' },
    // { value: 'Saloy' },
    // { value: 'Sirib' },
    { value: 'Tibuloy' },
    { value: 'Tibungco' },
    { value: 'Tigatto' },
    { value: 'Toril' },
    { value: 'Tugbok' },
    // { value: 'Tungakalan' },
    { value: 'Ubalde' },
    // { value: 'Ula' },
    { value: 'Vicente Hizon Sr.' },
    // { value: 'Waan' },
    // { value: 'Wangan' },
    // { value: 'Wilfredo Aquino' },
    // { value: 'Wines' },

];
export default {
    Barangay,
}